version: '3.1'

services:
  frontend:
    image: 'ivan7665/or-lab:frontendv1'
    ports:
      - '80:80'
    stdin_open: true
    tty: true
  backend:
    image: 'ivan7665/or-lab:backendv2'
    ports:
      - '8080:8080'
    depends_on:
      postgresDB:
        condition: service_healthy
    environment:
      - HOST=localhost
      - PORT=8080
      - DB_HOST=postgresDB
      - DB_PORT=5432
      - DB_DATABASE=ORLab
      - DB_USER=postgres
      - DB_PASSWORD=passoword
  postgresDB:
    image: 'ivan7665/or-lab:databasev2'
    container_name: postgresDB
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=passoword
    ports:
    - '5435:5432'
    expose:
      - '5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
