version: '3.1'

services:
  postgresDB:
    image: 'ivan7665/or-lab:v1.0'
    container_name: postgresDB
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=passoword
    ports:
    - '5435:5432'
